# Generated by Django 2.2.3 on 2019-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catg',
            field=models.CharField(choices=[('life', 'life'), ('thougts', 'thougts'), ('android', 'android'), ('web_dev', 'web_dev'), ('blog', 'blog')], default='blog', max_length=6),
        ),
    ]
